apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web-api.name" . }}
    helm.sh/chart: {{ include "web-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  db.host: "{{ .Release.Name }}-postgresql.default.svc.cluster.local"
  db.port: "{{ .Values.config.db.port }}"
  db.user: {{ .Values.config.db.user }}
  db.name: {{ .Values.config.db.name }}
  db.sslMode: {{ .Values.config.db.sslMode }}
  api.port: "{{ .Values.config.api.port }}"
  api.pageSize: "{{ .Values.config.api.pageSize }}"
