apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "web-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web-api.name" . }}
    helm.sh/chart: {{ include "web-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: port
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: user
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: name
            - name: DB_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: sslMode
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: port
            - name: API_PAGE_SIZE
                configMapKeyRef:
                  name: api
                  key: pageSize
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
